[2023-10-30 21:39:10,130: INFO: stage_01_get_data]: 
********************
[2023-10-30 21:39:10,130: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2023-10-30 21:39:10,136: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-10-30 21:39:10,137: INFO: common]: created directory at: data
[2023-10-30 21:39:15,866: INFO: stage_01_get_data]: filename: data\data.zip created with info X-GUploader-UploadID: ABPtcPopdgqWuRnlIzF3wpkLg-9HGN1cO0bZcjfxuTOKQ_xwcR2q_2RFckLIx-QWYi5ONIhbQPw5LmWxf7E1XaT18mm2
Expires: Mon, 30 Oct 2023 16:09:11 GMT
Date: Mon, 30 Oct 2023 16:09:11 GMT
Cache-Control: private, max-age=0
Last-Modified: Fri, 29 Jan 2021 02:06:52 GMT
ETag: "77bff8961310170c41bb1bb43b0595d0"
x-goog-generation: 1611886012431764
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 26429932
Content-Type: application/zip
x-goog-hash: crc32c=7PSVIw==
x-goog-hash: md5=d7/4lhMQFwxBuxu0OwWV0A==
x-goog-storage-class: MULTI_REGIONAL
Accept-Ranges: bytes
Content-Length: 26429932
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type
Access-Control-Expose-Headers: User-Agent
Server: UploadServer
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close


[2023-10-30 21:39:15,867: INFO: common]: yaml file: params.yaml loaded successfully
[2023-10-30 21:39:15,867: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2023-10-30 22:08:47,299: INFO: stage_01_get_data]: 
********************
[2023-10-30 22:08:47,299: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2023-10-30 22:08:47,302: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-10-30 22:08:47,302: INFO: common]: created directory at: data
[2023-10-30 22:08:47,302: INFO: stage_01_get_data]: Download start
[2023-10-30 22:08:47,302: ERROR: stage_01_get_data]: local variable 'filename' referenced before assignment
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 49, in <module>
    main(config_path=parsed_args.config)
  File "src/stage_01_get_data.py", line 38, in main
    logging.info(f"filename: {filename} is already present")
UnboundLocalError: local variable 'filename' referenced before assignment
[2023-10-30 22:09:44,560: INFO: stage_01_get_data]: 
********************
[2023-10-30 22:09:44,560: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2023-10-30 22:09:44,562: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-10-30 22:09:44,562: INFO: common]: created directory at: data
[2023-10-30 22:09:44,562: INFO: stage_01_get_data]: Download start
[2023-10-30 22:09:44,562: INFO: stage_01_get_data]: filename: data.zip is already present
[2023-10-30 22:09:44,562: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

[2023-10-30 22:10:13,366: INFO: stage_01_get_data]: 
********************
[2023-10-30 22:10:13,366: INFO: stage_01_get_data]: >>>>> stage GET_DATA started <<<<<
[2023-10-30 22:10:13,368: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-10-30 22:10:13,368: INFO: common]: created directory at: data
[2023-10-30 22:10:13,368: INFO: stage_01_get_data]: Download started...
[2023-10-30 22:10:13,368: INFO: stage_01_get_data]: filename: data.zip is already present
[2023-10-30 22:10:13,368: INFO: stage_01_get_data]: >>>>> stage GET_DATA completed!<<<<<

